PlannedServices/Controllers/AuthenticationController.cs
using PlannedServices.Common;
using PlannedServices.Entities.Contract;
using PlannedServices.Entities.V1;
using PlannedServices.Pages;
using PlannedServices.Services.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static PlannedServices.Infrastructure.Enums;
namespace PlannedServices.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly AbstractUserServices userService;        
        public AuthenticationController(AbstractUserServices _userService)
        {
            userService = _userService;
        }
        [HttpGet]
        public ActionResult SignUp()
        {
            //string EncodedID = Request.QueryString["id"];
            //string id = Base64Decode(EncodedID);
            //if (id != null || id != "")
            //{
            //    // find the user and
            //}
            //else
            //{
            //    //error msg
            //}
            return View();
        }


        [HttpPost]
        public ActionResult SignUp(User model)
        {
            string fullName = model.FirstName;
            var names = fullName.Split(' ');
            model.FirstName = names[0];
            model.LastName = names[1];

            SuccessResult<AbstractUser> result = userService.User_Upsert(model);
            if (result != null && result.Code == 200 && result.Item != null)
            {
                Session.Clear();
                ProjectSession.UserID = result.Item.Id;
                ProjectSession.UserName = result.Item.FirstName + " " + result.Item.LastName;
                ProjectSession.Email = result.Item.Email;


                HttpCookie cookie = new HttpCookie("UserLogin");
                cookie.Values.Add("Id", result.Item.Id.ToString());
                cookie.Values.Add("UserName", ProjectSession.UserName);
                cookie.Values.Add("Email", ProjectSession.Email);
                cookie.Expires = DateTime.Now.AddHours(1);
                Response.Cookies.Add(cookie);
                return RedirectToAction(Actions.SignUpPlan, Pages.Controllers.Authentication);
            }
            else
            {
                ViewBag.openPopup = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), result.Message);
            }
            return View();
        }
        [HttpGet]
        public ActionResult SignUpPlan()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SignUpPlan(string email, string password)
        {
            return View();
        }
        [HttpGet]
        public ActionResult SignUpSuccess()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SignUpSuccess(string email, string password)
        {
            return View();
        }

        [HttpGet]
        [ActionName(Actions.SignIn)]
        public ActionResult SignIn()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName(Actions.SignIn)]
        public ActionResult SignIn(User model)
        {
            SuccessResult<AbstractUser> result = userService.User_Login(model);
            if (result != null && result.Code == 200 && result.Item != null)
            {
                Session.Clear();
                ProjectSession.UserID = result.Item.Id;
                ProjectSession.UserName = result.Item.FirstName + " " + result.Item.LastName;
                ProjectSession.Email = result.Item.Email;


                HttpCookie cookie = new HttpCookie("UserLogin");
                cookie.Values.Add("Id", result.Item.Id.ToString());
                cookie.Values.Add("UserName", ProjectSession.UserName);
                cookie.Values.Add("Email", ProjectSession.Email);
                cookie.Expires = DateTime.Now.AddHours(1);
                Response.Cookies.Add(cookie);
                return RedirectToAction(Actions.Index, Pages.Controllers.Dashboard);
            }
            else
            {
                ViewBag.openPopup = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), result.Message);
            }
            return View();
        }
        public static string Base64Encode(string plainText)
        {
            var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
            return System.Convert.ToBase64String(plainTextBytes);
        }
        public static string Base64Decode(string base64EncodedData)
        {
            var base64EncodedBytes = System.Convert.FromBase64String(base64EncodedData);
            return System.Text.Encoding.UTF8.GetString(base64EncodedBytes);
        }
    }
}

PlannedServices/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlannedServices.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

PlannedServices/Views/Authentication/SignIn.cshtml
@using PlannedServices.Entities.V1;
@using PlannedServices.Pages;

@model User
@{
    ViewBag.Title = "Signin | NDIS";
    string userName = string.Empty;
    string password = string.Empty;
    Layout = "";
    if (Request.Cookies["UserLogin"] != null)
    {
        userName = Convert.ToString(Request.Cookies["UserLogin"].Values["UserName"]);
        password = Convert.ToString(Request.Cookies["UserLogin"].Values["Password"]);
    }
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Signin | NDIS</title>

    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/dist/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/dist/favicon-16x16.png">
    <link rel="manifest" href="~/Content/dist/site.webmanifest">
    <link rel="mask-icon" href="~/Content/dist/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheet -->
    <link rel="stylesheet" href="~/Content/dist/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.css">

    <!-- Main Stylesheet -->
    <link href="~/Content/dist/css/main.min.css" rel="stylesheet" />


</head>

<body>


    <div class="auth-columns">
        <div class="auth-columns-left">
            <div class="auth-columns-left-content">
                <img class="img-fluid mb-5" src="~/Content/dist/images/logo.png" alt="">
                <h2 class="fw-extrabold ">Sign in to your account</h2>
                <p class="mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores neque ullam necessitatibus.</p>
                @using (Html.BeginForm(Actions.SignIn, Controllers.Authentication, new { Area = "" }, FormMethod.Post, new { @id = "frmLogin", @class = "text-left", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @*<div class="form-auth-small">*@
                    <div class="form-group">
                        <label for="emailAddress">Email address</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control form-control-md", @placeholder = "john.doe@email.com", required = "required" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="passWord">Password</label>
                        @Html.PasswordFor(model => model.Password, new { @id = "password", @class = "form-control form-control-md", @placeholder = "Enter password here", required = "required" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="row no-gutters mb-4">
                        <div class="col">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="rememberMe">
                                <label class="custom-control-label" for="rememberMe">Remember me</label>
                            </div>
                        </div>
                        <div class="col text-right">
                            <a href="./forgot-password.html" class="fw-medium">Forgot password?</a>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mb-4">Sign In</button>

                }   
                <p>Or Don’t have an account? <a href="@Url.Action("SignUp", "Authentication")" class="fw-medium">Create an account</a></p>
            </div>
        </div>

        <div class="auth-columns-right">
            <div id="carouselIndicators" class="carousel slide mb-3">
                <ol class="carousel-indicators">
                    <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="carousel-caption">
                            <h5 class="text-white">First slide label</h5>
                            <p class="text-light">Some representative placeholder content for the First slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <h5 class="text-white">Second slide label</h5>
                            <p class="text-light">Some representative placeholder content for the second slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <h5 class="text-white">Third slide label</h5>
                            <p class="text-light">Some representative placeholder content for the Third slide.</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    @Html.Raw(ViewBag.openPopup)


    <!-- Scripts -->
    <script src="~/Content/dist/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/dist/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.js"></script>

    <!-- Main Js -->
    <script src="~/Content/dist/js/main.min.js"></script>

    <script>
         $('.carousel').carousel()
    </script>
</body>

</html>

PlannedServices/Views/Authentication/SignUp.cshtml
@using PlannedServices.Entities.V1;
@using PlannedServices.Pages;

@model User
@{
    ViewBag.Title = "Signup | NDIS";
    string userName = string.Empty;
    string password = string.Empty;
    Layout = "";
    if (Request.Cookies["UserLogin"] != null)
    {
        userName = Convert.ToString(Request.Cookies["UserLogin"].Values["UserName"]);
        password = Convert.ToString(Request.Cookies["UserLogin"].Values["Password"]);
    }
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Signup | NDIS</title>

    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/dist/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/dist/favicon-16x16.png">
    <link rel="manifest" href="~/Content/dist/site.webmanifest">
    <link rel="mask-icon" href="~/Content/dist/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheet -->
    <link rel="stylesheet" href="~/Content/dist/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.css">

    <!-- Main Stylesheet -->
    <link href="~/Content/dist/css/main.min.css" rel="stylesheet" />


</head>

<body>
    <div class="auth-columns">
        <div class="auth-columns-left">
            <div class="auth-columns-left-content">
                <img class="img-fluid mb-5" src="~/Content/dist/images/logo.png" alt="">
                <h2 class="fw-extrabold ">Sign up for your account</h2>
                <p class="mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores neque ullam necessitatibus.</p>
                @using (Html.BeginForm(Actions.SignUp, Controllers.Authentication, new { Area = "" }, FormMethod.Post, new { @id = "frmLogin", @class = "text-left", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <label for="FirstName">Full name</label>
                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control form-control-md", @placeholder = "Jhon Doe", required = "required" })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>

                    @*<div class="form-group">
                        <label for="FirstName">First name</label>
                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control form-control-md", @placeholder = "Jhon", required = "required" })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="LastName">Last name</label>
                        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control form-control-md", @placeholder = "Doe", required = "required" })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>*@
                    <div class="form-group">
                        <label for="emailAddress">Email address</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control form-control-md", @placeholder = "john.doe@email.com", required = "required" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="passWord">Password</label>
                        @Html.PasswordFor(model => model.Password, new { @id = "password", @class = "form-control form-control-md", @placeholder = "Enter password here", required = "required" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="row no-gutters mb-4">
                        <div class="col">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="rememberMe">
                                <label class="custom-control-label" for="rememberMe">I am agree to your <a href="">terms and conditions</a></label>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mb-4">Sign Up</button>

                }
                <p>Or Already have an account? <a href="@Url.Action("SignIn", "Authentication")" class="fw-medium">Sign in</a></p>
            </div>
        </div>

        <div class="auth-columns-right">
            <div id="carouselIndicators" class="carousel slide mb-3">
                <ol class="carousel-indicators">
                    <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="carousel-caption">
                            <h5 class="text-white">First slide label</h5>
                            <p class="text-light">Some representative placeholder content for the First slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <h5 class="text-white">Second slide label</h5>
                            <p class="text-light">Some representative placeholder content for the second slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <h5 class="text-white">Third slide label</h5>
                            <p class="text-light">Some representative placeholder content for the Third slide.</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>



    <!-- Scripts -->
    <script src="~/Content/dist/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/dist/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.js"></script>

    <!-- Main Js -->
    <script src="~/Content/dist/js/main.min.js"></script>

    <script>
         $('.carousel').carousel()
    </script>
</body>

</html>

PlannedServices/Views/Authentication/SignUpPlan.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Signup | NDIS</title>

    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/dist/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/dist/favicon-16x16.png">
    <link rel="manifest" href="~/Content/dist/site.webmanifest">
    <link rel="mask-icon" href="~/Content/dist/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheet -->
    <link rel="stylesheet" href="~/Content/dist/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.css">

    <!-- Main Stylesheet -->
    <link href="~/Content/dist/css/main.min.css" rel="stylesheet" />



</head>

<body>
    <div class="container py-4">
        <div class="row">
            <div class="col-12">
                <img class="img-fluid mb-5" src="~/Content/dist/images/logo.png" alt="">
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-8 text-center mb-5">
                <h2 class="fw-extrabold">Select How You Manage Your Plan?</h2>
            </div>

            <div class="col-lg-8 mb-5">
                <div class="custom-radio-btn-group d-flex flex-column flex-sm-row" data-toggle="buttons">
                    <label class="btn btn-white w-100 mr-3 p-4">
                        <div class="custom-control text-left custom-radio">
                            <input type="radio" id="planManage" name="manage-type" class="custom-control-input">
                            <label class="custom-control-label" for="planManage">
                                <span class="d-block h4 fw-bold mt-2">Plan Manage</span>
                                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestias asperiores officia atque repudiandae aperiam dicta repellendus perspiciatis qui.</p>
                            </label>
                        </div>
                    </label>
                    <label class="btn btn-white w-100 p-4">
                        <div class="custom-control text-left custom-radio">
                            <input type="radio" id="selfManage" name="manage-type" class="custom-control-input">
                            <label class="custom-control-label" for="selfManage">
                                <span class="d-block h4 fw-bold mt-2">Self Manage</span>
                                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestias asperiores officia atque repudiandae aperiam dicta repellendus perspiciatis qui.</p>
                            </label>

                        </div>
                    </label>
                </div>
            </div>

            <div class="col-lg-8 text-center mb-5">
                <a href="./signup-3.html" class="btn btn-primary btn-wide">Continue</a>
            </div>
        </div>
    </div>



    <!-- Scripts -->
    <script src="~/Content/dist/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/dist/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.js"></script>

    <!-- Main Js -->
    <script src="~/Content/dist/js/main.min.js"></script>

</body>

</html>

PlannedServices/Views/Authentication/SignUpSuccess.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- SEO & Metatags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no" /> <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <meta name=author content="">

    <title>Signup | NDIS</title>

    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/dist/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/dist/favicon-16x16.png">
    <link rel="manifest" href="~/Content/dist/site.webmanifest">
    <link rel="mask-icon" href="~/Content/dist/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <!-- Vendor Stylesheet -->
    <link rel="stylesheet" href="~/Content/dist/vendors/simplebar/dist/simplebar.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Content/dist/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.css">

    <!-- Main Stylesheet -->
    <link href="~/Content/dist/css/main.min.css" rel="stylesheet" />



</head>

<body>
    <div class="container py-4">
        <div class="row">
            <div class="col-12">
                <img class="img-fluid mb-5" src="~/Content/dist/images/logo.png" alt="">
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-8 text-center mb-5">
                <lottie-player class="mx-auto" src="https://assets4.lottiefiles.com/packages/lf20_y2hxPc.json" background="transparent" speed="1" style="width: 250px; height: 250px; " autoplay></lottie-player>
                <h2 class="fw-extrabold">Your request send successfully</h2>
                <p class="text-muted lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores, quaerat soluta nam ex dignissimos ab debitis laborum vitae omnis similique nostrum iure exercitationem sequi a.</p>

                <a href="#!" class="btn btn-primary btn-wide">Continue</a>

            </div>
        </div>
    </div>



    <!-- Scripts -->
    <script src="~/Content/dist/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/dist/vendors/simplebar/dist/simplebar.min.js"></script>
    <script src="~/Content/dist/vendors/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/moment.min.js"></script>
    <script src="~/Content/dist/vendors/daterangepicker/daterangepicker.js"></script>
    <script src="~/Content/dist/js/vendors/bootstrap-timepicker/timepicker.js"></script>

    <!-- Main Js -->
    <script src="~/Content/dist/js/main.min.js"></script>

    <script src=@Url.Content("https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js")></script>


</body>

</html>